CXX = g++
CXXFLAGS = -std=c++11 -Wall -O2
TARGET = robot_proto
OBJS = main.o robot.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

main.o: main.cpp robot.hpp
	$(CXX) $(CXXFLAGS) -c main.cpp

robot.o: robot.cpp robot.hpp
	$(CXX) $(CXXFLAGS) -c robot.cpp

clean:
	rm -f $(OBJS) $(TARGET)